# Generated by Django 5.0.4 on 2024-05-03 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('download', '0002_delete_uploadedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('uploaded_youtube_id', models.CharField(max_length=11)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.channel')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='download.videodetail')),
            ],
        ),
    ]
