# Generated by Django 5.0.4 on 2024-05-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('channel_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=16)),
                ('video_name', models.CharField(blank=True, max_length=80)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('link', models.TextField(blank=True)),
                ('convert_link', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.channel')),
            ],
            options={
                'unique_together': {('channel', 'video_id')},
            },
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('uploaded_youtube_id', models.CharField(max_length=11)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.channel')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='download.videodetail')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.channel')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='download.videodetail')),
            ],
        ),
    ]
